mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.t1.**.entity
  global-config:
    db-config:
      id-type: auto

t1:
  swagger:
    enabled: true
    title: 系统中心
    description: 系统中心接口文档
    version: 1.0
    base-package: com.t1.biz.*.controller
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: false
    ignoreTables:
      - sys_user
      - sys_user_role
      - sys_role_menu
    ignoreSqls:
      # 用户关联角色时，显示所有角色
      - com.t1.biz.system.mapper.RoleMapper.findAll
      # 用户列表显示用户所关联的所有角色
      - com.t1.biz.system.mapper.UserRoleMapper.findRolesByUserIds
  #审计日志
#  audit-log:
#    enabled: true
#    log-type: db
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://${t1.datasource.ip}:3306/logger-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#      username: ${t1.datasource.username}
#      password: ${t1.datasource.password}
